### ISSUE TITLE
R.empty is unbound identifier

### ISSUE THREAD

**Issue by gh16980973** [gregr/dbKanren#2]
https://github.com/gregr/dbKanren/blob/4ee3e54f3370590c70d60f8c5832ed496114a3e7/dbk/database.rkt#L335

database.rkt:335:23: R.empty: unbound identifier in: R.empty
  #(17018 7)

**Comment by gregr** [comment]
Thanks, I missed including the definition while using `git add -p`.  https://github.com/gregr/dbKanren/commit/ddc32dbecd74fb6e2db7e4b78a366d4e24bb9749
